### ISSUE TITLE
Python interface to link to most recent version of OpEn

### ISSUE THREAD

**Issue by alphaville** [alphaville/optimization-engine#135]
We should remove explicit versions from Jinja templates. Instead, the default version in auto-generated crates should be:

```toml
[dependencies]
optimization_engine = "{{open_version or '*'}}"
```
